#!/bin/bash

# GPG setup for signed Git commits.
#
# Distribution independent — gpg itself is installed by the per-distro scripts.
# An existing secret key is reused; a new one is only generated when there is
# none, and its passphrase is always typed interactively.

set -euo pipefail

# Get the directory where this script is located
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Source common utilities and logger
source "$SCRIPT_DIR/logger.sh"
source "$SCRIPT_DIR/utils.sh"

# Fingerprint of the key used for signing, filled in by select_or_generate_key
GPG_KEY_FPR=""

# gpg must be there; installing it is the per-distro script's job
check_gpg() {
    if command_exists gpg; then
        log_success "GPG available"
        log_info "GPG version: $(gpg --version | head -n1)"
        return 0
    fi

    log_error "gpg not found — install it first:"
    log_error "    Fedora:   sudo dnf install gnupg2"
    log_error "    openSUSE: sudo zypper install gpg2"
    log_error "    Arch:     sudo pacman -S gnupg"
    return 1
}

# Name and email come from the Git config — the signing key must match the
# committer identity or GitHub will not show the commit as verified.
resolve_identity() {
    GIT_NAME="$(git config --global user.name || true)"
    GIT_EMAIL="$(git config --global user.email || true)"

    if [[ -z "$GIT_NAME" || -z "$GIT_EMAIL" ]]; then
        log_error "git user.name / user.email are not set — set them first:"
        log_error "    git config --global user.name 'Your Name'"
        log_error "    git config --global user.email 'you@example.com'"
        return 1
    fi

    log_info "Signing identity: $GIT_NAME <$GIT_EMAIL>"
}

# Ask for the passphrase twice and compare. Empty is refused — an unprotected
# signing key on a remote box is worse than no signing at all.
prompt_passphrase() {
    if [[ ! -t 0 ]]; then
        log_error "No terminal available — the passphrase must be typed interactively"
        return 1
    fi

    local first second
    while true; do
        read -rsp "Passphrase for the new GPG key: " first || return 1
        echo
        read -rsp "Repeat passphrase: " second || return 1
        echo

        if [[ -z "$first" ]]; then
            log_error "An empty passphrase is not allowed for a signing key"
            continue
        fi

        if [[ "$first" != "$second" ]]; then
            log_error "Passphrases do not match, try again"
            continue
        fi

        GPG_PASSPHRASE="$first"
        return 0
    done
}

# Reuse a secret key for this email if there is one, otherwise generate one
select_or_generate_key() {
    GPG_KEY_FPR="$(
        gpg --list-secret-keys --with-colons "$GIT_EMAIL" 2>/dev/null |
            awk -F: '/^fpr/{print $10; exit}'
    )" || true

    if [[ -n "$GPG_KEY_FPR" ]]; then
        log_success "Reusing existing GPG key for $GIT_EMAIL"
        log_info "Fingerprint: $GPG_KEY_FPR"
        return 0
    fi

    log_info "Generating a new ed25519 GPG key for $GIT_EMAIL..."
    prompt_passphrase || return 1

    if ! gpg --batch --pinentry-mode loopback --passphrase "$GPG_PASSPHRASE" \
        --quick-generate-key "$GIT_NAME <$GIT_EMAIL>" ed25519 sign 2y; then
        unset GPG_PASSPHRASE
        log_error "gpg --quick-generate-key failed"
        return 1
    fi
    unset GPG_PASSPHRASE

    GPG_KEY_FPR="$(
        gpg --list-secret-keys --with-colons "$GIT_EMAIL" |
            awk -F: '/^fpr/{print $10; exit}'
    )"

    if [[ -z "$GPG_KEY_FPR" ]]; then
        log_error "Key was generated but could not be found afterwards"
        return 1
    fi

    log_success "GPG key generated"
    log_info "Fingerprint: $GPG_KEY_FPR"
}

# Point Git at the key and sign everything by default
configure_git_signing() {
    log_info "Configuring Git to sign with $GPG_KEY_FPR..."

    git config --global user.signingkey "$GPG_KEY_FPR"
    git config --global commit.gpgsign true
    git config --global tag.gpgsign true
    git config --global gpg.program "$(command -v gpg)"

    log_success "Git will sign every commit and tag"
    log_info "GPG_TTY is exported by shared/zsh.sh — without it gpg cannot prompt for the passphrase"
}

# gpg-agent is already a single per-user daemon shared by every terminal, so it
# needs no keychain the way ssh-agent does — only a cache long enough that a
# session of commits does not ask for the passphrase on every one of them.
configure_gpg_agent() {
    local GNUPG_DIR="$HOME/.gnupg"
    local AGENT_CONF="$GNUPG_DIR/gpg-agent.conf"

    mkdir -p "$GNUPG_DIR"
    chmod 700 "$GNUPG_DIR"

    if [[ -f "$AGENT_CONF" ]] && grep -qF "Generated by the dotenv setup" "$AGENT_CONF"; then
        log_success "gpg-agent already configured"
        return 0
    fi

    if [[ -f "$AGENT_CONF" ]]; then
        local BACKUP="$AGENT_CONF.backup.$(date +%Y%m%d-%H%M%S)"
        mv "$AGENT_CONF" "$BACKUP"
        log_warning "Existing gpg-agent.conf backed up to $BACKUP"
    fi

    cat > "$AGENT_CONF" <<'EOF'
# Generated by the dotenv setup (common/gpg.sh)
# Remember the passphrase for an hour of activity, eight hours at most
default-cache-ttl 3600
max-cache-ttl 28800
EOF
    chmod 600 "$AGENT_CONF"

    gpgconf --reload gpg-agent 2>/dev/null || log_warning "Could not reload gpg-agent — it picks the config up on next start"
    log_success "gpg-agent cache configured (1h idle, 8h max)"
}

# Upload the public key to GitHub with gh, skipping if it is already there
upload_key_to_github() {
    if ! command_exists gh; then
        log_warning "gh not installed — add the key manually at https://github.com/settings/keys"
        log_info "Export it with: gpg --armor --export $GPG_KEY_FPR"
        return 0
    fi

    if ! gh auth status >/dev/null 2>&1; then
        log_warning "gh is not authenticated — run: gh auth login"
        return 0
    fi

    if gh gpg-key list 2>/dev/null | grep -qF "${GPG_KEY_FPR: -16}"; then
        log_success "Key already uploaded to GitHub"
        return 0
    fi

    log_info "Uploading the public key to GitHub..."
    if gpg --armor --export "$GPG_KEY_FPR" | gh gpg-key add - --title "$(hostname)"; then
        log_success "GPG key uploaded to GitHub as '$(hostname)'"
    else
        log_warning "gh gpg-key add failed — add it manually at https://github.com/settings/keys"
    fi
}

# Scratch repo for the signing test; global so the EXIT trap can reach it after
# test_signing has returned.
TMP_REPO=""

cleanup_tmp_repo() {
    [[ -n "$TMP_REPO" ]] && rm -rf "$TMP_REPO"
    TMP_REPO=""
    return 0
}

# Sign a throwaway commit in a temporary repo to prove the whole chain works
test_signing() {
    # The trap matters here: this function stops at a passphrase prompt, so a
    # Ctrl-C is the likely ending, not the exception.
    TMP_REPO="$(mktemp -d)"
    trap cleanup_tmp_repo EXIT

    log_info "Signing a test commit (passphrase prompt follows)..."

    if git -C "$TMP_REPO" init -q &&
        git -C "$TMP_REPO" commit -q --allow-empty -m "dotenv signing test" &&
        git -C "$TMP_REPO" log -1 --pretty='%G?' | grep -qE '^[GU]$'; then
        log_success "Signing works"
    else
        log_warning "Test commit was not signed — check: gpg --list-secret-keys and echo \$GPG_TTY"
    fi

    cleanup_tmp_repo
}

main() {
    check_gpg
    resolve_identity
    select_or_generate_key
    configure_git_signing
    configure_gpg_agent
    upload_key_to_github

    echo ""
    log_success "GPG signing setup completed!"

    echo ""
    test_signing
}

# Run main only when executed directly, not when sourced
if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
    main "$@"
fi
