#!/bin/bash

# Check if command exists
command_exists() {
    command -v "$1" >/dev/null 2>&1
}

# Point ~/.zshrc at the shared Zsh config in this repo.
# The existing .zshrc is backed up, not appended to — the new one only sources
# the repo config, so edits in the repo apply everywhere.
setup_zshrc() {
    local ZSHRC="$HOME/.zshrc"
    local COMMON_DIR
    COMMON_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
    local CONFIG="$(dirname "$COMMON_DIR")/shared/zsh.sh"

    if [[ -f "$ZSHRC" ]] && grep -qF "shared/zsh.sh" "$ZSHRC"; then
        log_success ".zshrc already sources the shared config"
        return 0
    fi

    if [[ -f "$ZSHRC" ]]; then
        local BACKUP="$ZSHRC.backup.$(date +%Y%m%d-%H%M%S)"
        mv "$ZSHRC" "$BACKUP"
        log_warning "Existing .zshrc backed up to $BACKUP"
    fi

    cat > "$ZSHRC" <<EOF
# Generated by the dotenv setup
# The actual config lives in the repo — edit it there, not here
source "$CONFIG"
EOF

    log_success "Created .zshrc sourcing $CONFIG"
}

install_cargo_app() {
    local appname="${1}"
    log_info "Installing ${appname} via cargo..."

    if command_exists "$appname"; then
        log_success "${appname} already installed"
        log_info "${appname} version: $($appname --version)"
        return
    fi

    if ! command_exists cargo; then
        log_error "Cargo not found. Please install Rust first."
        return 1
    fi

    cargo install "$appname"
    log_success "${appname} installed successfully"
}
