#
# zephyr.toml - Zephyr theme, 2-line version (no right prompt)
#
add_newline = false

# Line 1: info, Line 2: prompt character
format = """
$directory\
$c\
$haskell\
$java\
$kotlin\
$nodejs\
$python\
$rust\
$git_branch\
${custom.git_status_dirty}\
$git_status\
$status\
$cmd_duration
$os\
$username\
$hostname\
$character"""

palette = "tokyo_night"

# Define custom colors
[palettes.tokyo_night]
black = '#15161e'
blue = '#7aa2f7'
cyan = '#7dcfff'
green = '#9ece6a'
purple = '#bb9af7'
red = '#f7768e'
white = '#a9b1d6'
yellow = '#e0af68'

[palettes.tokyo_night_256]
black = '16'
blue = '111'
cyan = '117'
green = '149'
purple = '141'
red = '210'
white = '146'
yellow = '179'

[palettes.wombat]
black = '#000000'
blue = '#5da9f6'
cyan = '#82fff7'
green = '#b1e969'
purple = '#e86aff'
red = '#ff615a'
white = '#dedacf'
yellow = '#ebd99c'

[palettes.wombat_256]
black = '0'
blue = '75'
cyan = '123'
green = '149'
purple = '171'
red = '203'
white = '188'
yellow = '223'

[character]
success_symbol = "[❯](purple)[❯](cyan)"
error_symbol = "[❯](yellow)[❯](red)"
vicmd_symbol = "[❮](purple)[❮](cyan)"

[python]
format = '[(\($virtualenv\) )]($style)'
style = 'green'

[nodejs]
format = "[ ($version) ]($style)"
style = "green"

[kotlin]
symbol = ""
style = "cyan"
format = '[$symbol( $version) ]($style)'

[golang]
symbol = ""
style = "cyan"
format = '[$symbol( $version) ]($style)'

[c]
symbol = " "
style = "cyan"
format = '[$symbol( $version) ]($style)'

[docker_context]
symbol = ""
format = '[$symbol( $context) ]($style)'
style = "blue"

[rust]
format = "[ ($version) ]($style)"
style = "blue"

[directory]
style = "blue"
truncation_length = 0
truncation_symbol = ""
fish_style_pwd_dir_length = 0
truncate_to_repo = false

[git_branch]
format = '[ $branch]($style)'
style = 'yellow'

[git_status]
style = "cyan"
format = " [$all_status$ahead_behind ]($style)"
ahead = '[⬆${count}](bold purple) '
behind = '[⬇${count}](bold purple) '
staged = '[✚${count}](green) '
deleted = '[✖${count}](red) '
renamed = '[➜${count}](purple) '
stashed = '[≡${count}](cyan) '
untracked = '[${count}](white) '
modified = '[✱${count}](blue) '
conflicted = '[═${count}](yellow) '
diverged = '⇕ '
up_to_date = ''

[custom.git_status_dirty]
when = 'test -n "$(git status --porcelain 2>/dev/null)"'
symbol = ""
style = "white"
format = "[$symbol]($style)"
shell = ["sh"]

[cmd_duration]
format = ' [$duration]($style)'

[status]
disabled = false
symbol = ' ✘'

[os]
disabled = false
style = "blue"
format = '[$symbol ]($style)'

[os.symbols]
Windows = ""
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
EndeavourOS = "󰣇"

[username]
show_always = true
style_user = "green"
style_root = "red"
format = '[$user]($style)'

[hostname]
ssh_only = false
style = "white"
format = '[@$hostname ]($style)'
